### ISSUE TITLE
Leaking memory in google chrome

### ISSUE THREAD

**Issue by fourtf** [FrankerFaceZ/FrankerFaceZ#103]
**Web Browser**:
Google Chrome

**Do you use BetterTTV or other Twitch extensions**:
No

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

Heap snapshot from chrome:
![bpas7](https://cloud.githubusercontent.com/assets/6320036/22799157/0f915104-ef05-11e6-8071-582938d495cc.png)

**Bug / Idea**:
FFZ is leaking memory which causes the website to crash after a certain amount of time. We believe that it is somehow related to the ffz supporters but that's only an idea.

**Steps to Reproduce (if Applicable)**:
Open any twitch page in the browser and in incognito mode and open the chrome taskmanager. The amount of ram used by the normal tab will steadily increase.

**Comment by SirStendec** [comment]
I'm not really sure what's going on here. I'm unable to reproduce any memory leaks. What extensions are you using? All of them that could be running anything on that page, that is.

**Comment by nuuls** [comment]
https://www.twitch.tv/directory/following/live
looks like this for me <img src="https://i.nuuls.com/WqmRL.png">(its 7:30 pm right now) both are constantly growing in memory usage. I do have FFZ addon pack, and im pretty sure it cant be adblock or any other extension since all other websites are running just fine.

**Comment by SirStendec** [comment]
So, it looks to be a problem with uncollected DOM nodes rather than a JS leak? Hmm. I've just pushed a change that optimizes the code for rendering stream up-time. Let me know if you see an improvement on v3.5.428, please.

**Comment by nuuls** [comment]
yeah that would make sense. I am following a lot of channels (30 live right now) and the site is auto updating every few minutes, maybe something is not getting removed properly?

**Comment by nuuls** [comment]
looks like its fixed for me <img src="https://cdn.betterttv.net/emote/566c9fde65dbbdab32ec053e/1x">

**Comment by SirStendec** [comment]
Alright, I know what was happening then. I was setting HTML to an element when I shouldn't have on a frequent timer. That's cleaned up now so this should be closed.

**Comment by Fr0zt** [comment]
This is not fixed for me. Memory for Chrome just keeps bloating when on https://www.twitch.tv/directory/following/live

Version 3.5.429

**Comment by SirStendec** [comment]
@Fr0zt What other extensions, if any, do you use? Can you please post your FFZ debugging information? (Open the FFZ menu, go to the About page, click Logs. Paste that link.)

**Comment by Fr0zt** [comment]
Just ublock origin.

http://putco.de/NTUwOQ.log

**Comment by Fr0zt** [comment]
Looks like it may be unrelated to FFZ... "GPU process" is the culprit now.

This is after 30 minutes:
![image](https://cloud.githubusercontent.com/assets/10720170/23090541/3f619a46-f56e-11e6-9286-38bbb2c423b7.png)

**Comment by SirStendec** [comment]
Yeah, that's likely unrelated to FFZ. Just Chrome being Chrome. Looks like the memory of your actual tabs is fine. Well within the range I expect.
