### ISSUE TITLE
FFZ not working properly.

### ISSUE THREAD

**Issue by crankgud** [FrankerFaceZ/FrankerFaceZ#1637]
Add-on not working as intended. Acting as if its not installed, without access for the button to open and view of the dashboard.
Due personal configuration with chat on the left side, now it blocks part of the screen acting as if chat is collapse, also no access to the emojis aside Twitch's default list. And many other functions missing.

Images for example purpose:
![Image](https://github.com/user-attachments/assets/f018c8d5-a5d3-4cf8-87a0-9dfe3eb8782c)
![Image](https://github.com/user-attachments/assets/ecd33088-cce5-4bfe-a1bd-7381b59f271f)

Environment (please complete the following information):

- OS: W10.
- Browser: Chrome
- Version:  133.0.6943.142 
- FrankerFaceZ Version: 4.77.0.1
- Other Extensions that interact with twitch: ublock Origin, ublock Origin Lite, Gumbo: Twitch Companion.

**Comment by culi1997** [comment]
same. still working in incognito Chrome (not logged in) though

**Comment by culi1997** [comment]
clearing my cookies fixed it

**Comment by NearCry91** [comment]
> clearing my cookies fixed it

I have the same problem. Clearing cookies didn't help.

Environment (please complete the following information):

    OS: W10.
    Browser: Firefox
    Version: 136.0.1
    FrankerFaceZ Version: 4.0
    Other Extensions that interact with twitch: ublock Origin, Gumbo: Twitch Companion.

**Comment by just-ero** [comment]
Same issue here. Clearing cookies didn't fix it. It appears as if FFZ is simply not installed at all. No option to open the menu, no emotes, none of the other features work.

```
OS: Win11 Pro
Browser: Edge
Version: 134.0.3124.51
FrankerFaceZ Version: 4.77.0.1
Other Extensions that interact with Twitch: ublock Origin
```

**Comment by yessser** [comment]
for firefox users :  
f12 --> storage tab (may be under arrows >> button) --> cookies --> twitch.tv and remove  unique_id and unique_id_durable

**Comment by mogzol** [comment]
@CrescentB's fix worked for me yesterday, but the issue came back today and repeating those steps didn't fix it. But I was able to fix it by disabling the regular FrankerFaceZ extension and installing the nightly version: https://chromewebstore.google.com/detail/frankerfacez-nightly/jgnjpfcdneiofkjkidlokfipfaignogj

So I assume whenever the nightly update comes out for the regular version this will be fixed for everyone. In the meantime, use the nightly version.

**Comment by SirStendec** [comment]
The problems stopping FFZ from loading are all resolved at this point, except for Firefox because Firefox is very slow at reviews. I wrote a post about Firefox here: #1644

**Comment by RafaelCV** [comment]
> for firefox users : f12 --> storage tab (may be under arrows >> button) --> cookies --> twitch.tv and remove unique_id and unique_id_durable

Worked well for me, thank you very much.

**Comment by djd1ed** [comment]
I'm having the same problem, it just started today. Deleting the cookies mentioned did not help. (I even deleted all of them) Where the FFZ menu logo is supposed to be is an image text that just says "control center there are 40 new settings."

**Comment by charlesmadere** [comment]
This issue is back today, and persists even through Twitch cookie deletion 😭 I even went through and deleted *every* Twitch cookie, not just the specific `unique_id` and `unique_id_durable` cookies. For me, unfortunately FFZ doesn't seem to load or work at all right now.

**Comment by RafaelCV** [comment]
Yes, seems for firefox it stopped work again, in chrome still working, but not for firefox anymore, it still working since i use the chat on the left, and it still on left, but no config button, even deleting the ids.

**Comment by marcelwirtz** [comment]
Have the same Issue on Firefox and Cookie deletion does not fixing it.

**Comment by SirStendec** [comment]
Commenting that it's still not working on Firefox is not helping anything. I know it's not working.

It won't work till Firefox approves our update. Locking this thread to silence notifications.
