### ISSUE TITLE
Audio compressor sometimes pitches the audio up. Only noticed this when watching vods

### ISSUE THREAD

**Issue by Ruzmuz** [FrankerFaceZ/FrankerFaceZ#747]
**Describe the bug**
Sometimes when watching a VOD with the audio compressor on, the audio gets pitched up a bit.

**To Reproduce**
Steps to reproduce the behavior (This method only worked for me a single time, after that i couldn't reproduce it like this):
1. Go to any twitch vod
2. Enable Audio Compressor
3. Play the vod for a couple seconds, then pause it for a few minutes,
4. Press play and the audio might get pitched up.

**Expected behavior**
I expected the audio to stay in its original pitch.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 79
 - Other Extensions: BTTV, Ublock

**Additional context**
For some reason I can no longer reproduce this bug using the method in this report. But i've had this bug happen to me atleast 3 times in the last day.

**Comment by AceKuper** [comment]
I can confirm experiencing the same bug. It goes away if i reload the page. But for me it even happens with the compressor disabled and i don't need to pause it for that long. In fact just selecting different positions on video timeline can cause this bug to happen.

**Comment by GoaLitiuM** [comment]
Same issue here with only vods. Pausing the video while the compressor is enabled, doing some other tasks with the browser for a minute or two, and then unpausing it, the audio will be pitched up. Edge v81.

**Comment by itsmedoggo** [comment]
Issue is still present. It's probably worth mentioning that the audio pitch-up is actually a side effect of the video speed increasing (presumably because it thinks it needs to "catch up"). This happens regardless of the "Player->General->Allow the player to speed up to reduce delay" setting being on or off.

**Comment by Ruzmuz** [comment]
I have started seeing the issue happen to livestreams now aswell and not only VOD's, even when the audio compressor hasn't been enabled at all for the stream. It happens every time im opening a new stream in a new tab while already having a stream running in another tab.
It usually gets fixed by pressing the "reset player" button.

**Comment by SHsuperCM** [comment]
Issue still present, Chrome 83.0.4103.61..
Any progress on it?
